### ISSUE TITLE
node-gyp rebuild fails for 0.2.3

### ISSUE THREAD

**Issue by sundaymtn** [astro/node-stringprep#51]
CentOS 6.3
node 0.10.24
npm 1.3.21
node-gyp 0.12.2

I can reproduce via "npm install node-stringprep@0.2.3" anywhere on my system,
tried to attach log but only images are supported, see interesting part of output below
Thanks,
Seth

```
gyp: Call to 'which icu-config > /dev/null || echo n' returned exit status 0.
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/scarter/Projects/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:337:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 2.6.32-431.el6.x86_64
gyp ERR! command "node" "/home/scarter/Projects/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/scarter/Projects/local/lib/node_modules/node-stringprep
gyp ERR! node -v v0.10.24
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm ERR! node-stringprep@0.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-stringprep@0.2.3 install script.
npm ERR! This is most likely a problem with the node-stringprep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-stringprep
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 2.6.32-431.el6.x86_64
npm ERR! command "/home/scarter/Projects/local/bin/node" "/home/scarter/Projects/local/bin/npm" "i" "-g" "node-stringprep"
npm ERR! cwd /home/scarter/Projects/local/bin
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/scarter/Projects/local/bin/npm-debug.log
npm ERR! not ok code 0
```

**Comment by EternallLight** [comment]
Right, libicu-devel worked for me too on CentOS release 6.6 (Final). Thanks.

**Comment by Oneway102** [comment]
Great.  After running *yum install libicu-devel* to install libicu my problem got resolved!
